In [2]:
import numpy as np
data = np.random.randn(2,3)
data

array([[ 0.42269606, -0.84701177,  0.95064436],
       [ 0.74973572, -1.63976451,  0.30617713]])

In [2]:
data*10

array([[-4.11607168, 18.94812429,  4.11590397],
       [-8.83661273, -6.01870163,  1.25813621]])

In [3]:
data1 = [2,3,4,5,6]
arr1 = np.array(data1)
arr1

array([2, 3, 4, 5, 6])

In [5]:
data.ndim  # 维度

2

In [6]:
data.shape  # 行和列 

(2, 3)

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
np.eye(3)  # 特征矩阵，对角线为1,其余位置为0

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.identity(4) # 特征矩阵，对角线为1,其余位置为0

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
arr = np.array([1,2,3,4,5]) # 整数转为浮点数
arr


array([1., 2., 3., 4., 5.])

In [15]:
float_arr = arr.astype(np.float64) # astype转换数据类型
float_arr.dtype

dtype('float64')

In [18]:
# 浮点数转整数，小数位数会被消除
arr_1 = np.array([3.7, 1.2, 3.0, 4.4])
arr_1.astype(np.int32)
arr_1

array([3.7, 1.2, 3. , 4.4])

In [3]:
# 切片
arr_2 = np.arange(10)
arr_2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr_2[5:8]

array([5, 6, 7])

In [7]:
arr_2[5:8] = 12
arr_2

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [8]:
arr_slic = arr_2[5:8] # 会在原数上进行更改，不改变原值只有使用copy()函数
arr_slic[1] = 12345
arr_2

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [10]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])  # 二维数组
arr2d[2]

array([7, 8, 9])

In [11]:
arr2d[0][2]  # 只取一个值

3

In [12]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,1,2]]])
arr3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 1, 2]]])

In [13]:
old_values = arr3d[0].copy() # 拷贝不改变原值
arr3d[0] = 42  # 改变第一行的值
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [ 0,  1,  2]]])

In [14]:
arr3d[0] = old_values
arr3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 1, 2]]])

In [15]:
arr3d[0,1]  # 第一维的第二个值

array([4, 5, 6])

In [16]:
arr2d[:2]  # 取前2行

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr2d[:2,1:]  # 取前2行，1列后

array([[2, 3],
       [5, 6]])

In [18]:
arr2d[1,:2] # 第1行，列前两个值

array([4, 5])

In [19]:
arr2d[:2,2] # 前2行，第2列

array([3, 6])

In [20]:
arr2d[:, :1] # 所有行，前1列

array([[1],
       [4],
       [7]])

In [22]:
arr2d[:2, 1:]=0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [31]:
arr4d = np.empty((8,4))
for i in range(8):
    arr4d[i] = i
arr4d

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [28]:
arr4d[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [33]:
arr4d[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [34]:
arr5d = np.arange(32).reshape((8,4))
arr5d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [36]:
arr5d[[1,5,7,2],[0,3,1,2]] # (1,0)(5,3)(7,1)(2,2)4个元素被选中

array([ 4, 23, 29, 10])

In [37]:
arr5d[[1,5,7,2]][:,[0,3,1,2]]  # 前面表示行号，后面表示列号

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [38]:
# 转置
arr6d = np.arange(15).reshape((3,5))
arr6d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [39]:
arr6d.T  # 矩阵转置

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [40]:
np.dot(arr6d.T, arr6d)  # 矩阵相乘

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [41]:
arr7d = np.arange(16).reshape((2,2,4)) # 高维2， 行，列
arr7d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [43]:
arr7d.transpose((1,0,2))  # 轴重新排列，原先第二个轴变为第一个，原先的第一个轴变成第二个，最后一个轴没有变

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [44]:
arr7d.swapaxes(1,2) # 接收一个轴进行编号作为参数，并对轴进行调整用于重组数据，一个轴只有两列

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [2]:
# 通用函数，一元通用函数和二元通用函数
arr7d = np.arange(10)
np.sqrt(arr7d)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [3]:
np.exp(arr7d)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [4]:
# 二元通用函数
x = np.random.randn(8)
y = np.random.randn(8)
np.maximum(x,y)

array([ 0.644088  ,  0.4910067 , -0.0115536 ,  1.47443595,  0.89690743,
        0.44112768,  0.04095402,  0.44395777])

In [7]:
arr8d = np.random.randn(7)*5
remainder, whole_part = np.modf(arr8d)  # 一个是小数部分，一个是整数部分
arr8d

array([ 4.56247628, -7.26441498,  0.75392407,  3.29028204, -4.68315102,
       -1.75045769, -4.84855816])

In [8]:
whole_part

array([ 4., -7.,  0.,  3., -4., -1., -4.])

In [9]:
remainder

array([ 0.56247628, -0.26441498,  0.75392407,  0.29028204, -0.68315102,
       -0.75045769, -0.84855816])

In [10]:
points = np.arange(-5,5,0.01) 
xs, ys = np.meshgrid(points, points)  # meshgrid接收两个一维数组
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [11]:
z = np.sqrt(xs**2 + ys**2)

In [12]:
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

In [17]:
import matplotlib.pyplot as plt
plt.imshow(z, cmap=plt.cm.gray);plt.colorbar()

In [18]:
plt.title("image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

Text(0.5, 1.0, 'image plot of $\\sqrt{x^2 + y^2}$ for a grid of values')

In [19]:
# 条件逻辑作为数组操作
xarr = np.array([1.1, 1.2, 1.3])
yarr = np.array([2.1, 2.2, 2.3])
cond = np.array([True, False, True])
result = np.where(cond, xarr, yarr)  # 相当于x if condition else y
result

array([1.1, 2.2, 1.3])

In [21]:
# np.where 第二、三个参数即可以同等大小的数组，也可以是标量
arr8d = np.random.randn(4,4)
arr8d

array([[-1.49403382, -0.27470648,  1.36877565,  3.31375875],
       [-0.42324497,  0.6102758 , -0.55767847, -0.99441515],
       [ 0.14487204,  1.60122995,  0.78599348, -0.13791871],
       [-0.84845013,  1.28351087, -0.4223365 ,  2.23160134]])

In [22]:
np.where(arr8d>0, 2, -2) # 大于0用2代替，小于0用-2代替

array([[-2, -2,  2,  2],
       [-2,  2, -2, -2],
       [ 2,  2,  2, -2],
       [-2,  2, -2,  2]])

In [23]:
np.where(arr8d>0, 2, arr8d) # 大于0 用2代替

array([[-1.49403382, -0.27470648,  2.        ,  2.        ],
       [-0.42324497,  2.        , -0.55767847, -0.99441515],
       [ 2.        ,  2.        ,  2.        , -0.13791871],
       [-0.84845013,  2.        , -0.4223365 ,  2.        ]])

In [24]:
arr8d.mean() # 平均值

0.38670210254471205

In [25]:
np.mean(arr8d)

0.38670210254471205

In [26]:
arr8d.sum()

6.187233640715393

In [27]:
arr8d.mean(axis=0) # 行的均值

array([-0.65521422,  0.80507753,  0.29368854,  1.10325656])

In [28]:
arr8d.sum(axis=1)  #列求和

array([ 2.9137941 , -1.3650628 ,  2.39417675,  2.24432558])

In [29]:
# cumsum--从0开始元素累积和  cumprod--从1开始元素累积和 不是聚合函数 
arr9d = np.array([1,2,3,4,5,6])
arr9d.cumsum()

array([ 1,  3,  6, 10, 15, 21])

In [30]:
# 排序
arr10d = np.random.randn(6)
arr10d

array([-0.13859876, -0.56561461,  0.32832103, -0.66912714,  1.47605599,
        0.02067722])

In [32]:
arr10d.sort()
arr10d

array([-0.66912714, -0.56561461, -0.13859876,  0.02067722,  0.32832103,
        1.47605599])

In [33]:
arr11d = np.random.randn(5,3)
arr11d

array([[-1.9539934 , -0.42447909, -0.57736239],
       [ 0.26634592, -0.10366139,  0.40419218],
       [-0.56507384, -0.76899079,  0.84377097],
       [ 0.91737553, -1.92520302,  0.76233245],
       [ 1.50953323, -1.44282436, -0.23698889]])

In [34]:
arr11d.sort(1)  # 所有行按列进行排序
arr11d

array([[-1.9539934 , -0.57736239, -0.42447909],
       [-0.10366139,  0.26634592,  0.40419218],
       [-0.76899079, -0.56507384,  0.84377097],
       [-1.92520302,  0.76233245,  0.91737553],
       [-1.44282436, -0.23698889,  1.50953323]])

In [3]:
# 唯一值
names =np.array(['Bob', 'Joe', 'Will', 'Bob'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [4]:
ints = np.array([2,2,3,1,4,4])
np.unique(ints)

array([1, 2, 3, 4])

In [5]:
# 检查一个数组中的值是否在另外一个数组中
np.in1d(ints, [2,3])

array([ True,  True,  True, False, False, False])

In [7]:
# numpy保存和加载数据
arr_12 = np.arange(10)
np.save('./data/some_array', arr_12)

In [8]:
np.load('./data/some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# 矩阵乘
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[1,2],[-1,3],[4,5]])
x.dot(y)

array([[11, 23],
       [23, 53]])

In [11]:
np.dot(x,y)

array([[11, 23],
       [23, 53]])

In [12]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [14]:
# 矩阵分解
from numpy.linalg import inv, qr
X = np.random.randn(5,5)
mat = X.T.dot(X)
mat

array([[ 3.35130813,  3.52195783,  2.68515577,  0.77893539, -1.11329337],
       [ 3.52195783,  6.04038211,  2.89597273,  1.23521083, -0.94759849],
       [ 2.68515577,  2.89597273,  4.37618933, -0.02026594, -1.971382  ],
       [ 0.77893539,  1.23521083, -0.02026594,  3.75567118,  1.25876286],
       [-1.11329337, -0.94759849, -1.971382  ,  1.25876286,  1.3373975 ]])

In [15]:
inv(mat) # 逆矩阵

array([[  3.20437172,  -1.05774002,   5.06978448,  -5.0207077 ,
         14.11656242],
       [ -1.05774002,   0.62640794,  -1.64025353,   1.40417544,
         -4.17608223],
       [  5.06978448,  -1.64025353,  14.26506461, -12.42811452,
         35.78277696],
       [ -5.0207077 ,   1.40417544, -12.42811452,  11.66625784,
        -32.48438822],
       [ 14.11656242,  -4.17608223,  35.78277696, -32.48438822,
         92.85966999]])

In [16]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -8.48705155e-16, -6.90576319e-15,
         5.54882730e-15, -1.77432886e-15],
       [ 2.11697473e-15,  1.00000000e+00, -8.28904370e-17,
         4.16713448e-15, -3.96850967e-15],
       [ 3.68957286e-15, -2.52007631e-15,  1.00000000e+00,
         5.08809595e-15,  1.88575458e-14],
       [-5.73390615e-16,  1.33699733e-16,  1.96980183e-15,
         1.00000000e+00,  2.88843810e-15],
       [-3.83508230e-15,  7.93902405e-16, -5.11157946e-15,
         1.29801467e-15,  1.00000000e+00]])

In [17]:
q, r = qr(mat) # 矩阵分解
r

array([[-5.7176636 , -7.49788416, -5.79396955, -1.47445691,  2.25096832],
       [ 0.        , -1.86614116,  1.05905948, -1.35936672, -0.97051799],
       [ 0.        ,  0.        , -1.98565358,  2.05519776,  1.48710713],
       [ 0.        ,  0.        ,  0.        , -3.09462565, -1.08466005],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.00945956]])

In [18]:
# 随机数比python自带的随机数生成量大
samples = np.random.normal(size=(4,4))
samples

array([[ 0.95594967, -1.3178576 ,  0.41643245,  0.63947254],
       [-0.21733871, -0.5288873 , -2.56777605,  0.37624778],
       [ 0.87940265, -2.82796035,  0.93502968, -1.09841028],
       [-1.07624863,  0.14676572, -1.34245987, -1.04379545]])

In [19]:
np.random.seed(1234) # 更改随机数的种子
xq = np.random.normal(size=(4,))
xq

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 ])

In [20]:
xq_1 = np.random.normal(size=(4,))
xq_1

array([-0.72058873,  0.88716294,  0.85958841, -0.6365235 ])

In [21]:
# 避免全局状态，使用numpy.random.RandomState创建一个随机数生成器
rng =np.random.RandomState(1234)
rng.randn(10)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])

In [23]:
# 随机漫步示例
import random
position = 0
walk = [position]
steps = 1000
for i in range(steps):
    step = 1 if random.randint(0,1) else -1
    position += step
    walk.append(position)
walk

[0,
 -1,
 0,
 -1,
 0,
 1,
 2,
 3,
 2,
 1,
 2,
 1,
 2,
 3,
 4,
 3,
 4,
 5,
 4,
 5,
 6,
 7,
 6,
 5,
 6,
 7,
 6,
 7,
 6,
 7,
 8,
 7,
 6,
 7,
 8,
 7,
 8,
 9,
 10,
 9,
 8,
 9,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 6,
 5,
 4,
 5,
 4,
 3,
 2,
 1,
 0,
 -1,
 0,
 1,
 0,
 1,
 0,
 -1,
 -2,
 -3,
 -4,
 -3,
 -2,
 -3,
 -2,
 -3,
 -4,
 -3,
 -2,
 -1,
 0,
 -1,
 0,
 -1,
 -2,
 -1,
 0,
 -1,
 -2,
 -1,
 -2,
 -1,
 0,
 1,
 0,
 -1,
 0,
 1,
 0,
 -1,
 -2,
 -3,
 -2,
 -1,
 0,
 -1,
 0,
 -1,
 -2,
 -3,
 -4,
 -5,
 -4,
 -5,
 -6,
 -7,
 -6,
 -7,
 -6,
 -5,
 -4,
 -5,
 -6,
 -5,
 -4,
 -3,
 -4,
 -5,
 -6,
 -5,
 -4,
 -3,
 -2,
 -1,
 0,
 -1,
 0,
 1,
 2,
 1,
 2,
 3,
 2,
 3,
 4,
 3,
 4,
 3,
 4,
 3,
 2,
 1,
 0,
 1,
 0,
 1,
 2,
 3,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 7,
 6,
 5,
 4,
 3,
 4,
 5,
 4,
 5,
 6,
 5,
 4,
 5,
 4,
 3,
 4,
 3,
 2,
 1,
 0,
 1,
 2,
 1,
 0,
 1,
 2,
 1,
 0,
 1,
 2,
 1,
 2,
 3,
 4,
 5,
 6,
 5,
 4,
 3,
 4,
 3,
 2,
 1,
 0,
 -1,
 -2,
 -3,
 -4,
 -3,
 -2,
 -1,
 0,
 -1,
 0,
 -1,
 0,
 1,
 0,
 1,
 2,
 1,
 0,
 -1,
 0,
 -1,
 0,
 -1,

In [ ]:
plt.plot(walk[:100])